### ISSUE TITLE
Implement a queue

### ISSUE THREAD

**Issue by gwennlbh** [SourCreamCulture/dogebeatz#3]
This could allow for multiple people queueing music up instead of abruptly ending the previous track before its end.

Proposed CLI:

```
-queue add <url|query>
-queue rm <index>
-queue ls
0: title of song currently playing (or paused)
1: next song
2: next next song
etc.
```
## Implementation details

You could use https://textdb.dev/ to store the current queue as a JSON file (since the bot is only in one room, a single file can be used).

The file's UUID will need to be stored in a .env so that no one can edit the data from the website

**Comment by SourCreamCulture** [comment]
If you want to @ewen-lbh you could try and implement this. Just fork the repo and create a pull request :) Or just message back on this issue if you don't want to and I can try to implement it.

**Comment by rehhouari** [comment]
I'm on it :)

btw @SourCreamCulture if you'd like to take a look at [my fork](https://github.com/rehhouari/dogebeatz) to see the changes I've made so far. I found it confusing how to set this project locally since I didn't make any plugins for dogehouse before so made it easier for those who want to contribute by adding steps to run locally.

I was going to make a pull request with those changes only, but forgot and now I gotta wait till I finish queues because they're not  working yet 😅

**Comment by SourCreamCulture** [comment]
@rehhouari Nice your fork looks good :) I like the contributor part too, that will make it easier for new contributors. Thanks for working on getting queues done it will be an epic addition to the bot 👍

**Comment by rehhouari** [comment]
Done in #4 :D

**Comment by SourCreamCulture** [comment]
Epic :) It looks really good, I'll merge it now

**Comment by rehhouari** [comment]
> Epic :) It looks really good, I'll merge it now

Thankss but wait help isn't working all of a sudden

**Comment by SourCreamCulture** [comment]
whoops i merged it, didn't see this message

**Comment by SourCreamCulture** [comment]
@rehhouari just open another pull request when you fix it
